### ISSUE TITLE
Import mail.py and photos.py only if required

### ISSUE THREAD

**Issue by slimninja** [treymo/google-photos-takeout#5]
Thanks for this! Downloaded this script only to extract attachments from my mbox file. Since I was just using the mail.py utility, I didn't install the requirements for photos.py, however, I had to comment out the `import photos` in order for the script to run.

For people in a similar situation, it would be helpful if the program only imported dependencies required for the run. This could be done by removing the imports from the beginning of the script, and import within the methods themselves.

Removed:
```
import mail
import photos
```

Changed:
```
def _maybe_organize_photos_takeout(takeout_dir):
    if not takeout_dir:
        print('Invalid (or no) Photos takeout archive directory specified. Not '
              'extracting photos from archives.')
        return
    else:
        organize_photos = input('Organize Photos takeout archives? y/n: ')
        organize_photos = distutils.util.strtobool(organize_photos)
        if not organize_photos:
            return
    import photos
    photos.organize_photos_takeout(takeout_dir)


def _maybe_extract_email_attachments(mbox_file_path):
    if (mbox_file_path and os.path.isfile(mbox_file_path) and
            mbox_file_path.endswith('.mbox')):
        answer = input('Extract mailbox attachments? y/n: ')
        answer = distutils.util.strtobool(answer)
        if answer:
            import mail
            mail.extract_mail_attachments(mbox_file_path)
    else:
        print('Invalid (or no) .mbox path specified. Not extracting email '
              'attachments.')
```

**Comment by slimninja** [comment]
Additionally... Needed to make a few changes to handle my mbox extraction with no errors

- Replace illegal windows characters or line breaks in filename e.g. `Illegal windows char. Renamed "=?UTF-8?B?UGF5bWVudF8xNTM5?==?UTF-8?B?MzA0LnBkZg==?=" to "=UTF-8BUGF5bWVudF8xNTM5==UTF-8BMzA0LnBkZg==="`
- Appended current epoch timestamps on collisions 
- Skip if attachment.get_filename() returned None
- Printed/continued on any additional errors - Only error unhandled was `a bytes-like object is required, not 'NoneType'`

```
"""
Module for extracting all attachments from an mbox archive.
"""

import mailbox
import os
import re
import time


def strip_illegal_char(string, seperator=''):
	string = str(string)
	parsed = re.sub(r'[\<,\>,\:,\",\/,\\,\|,\?,\*,\n,\t]', seperator, string)
	if string != parsed:
		print('Illegal windows char. Renamed "{}" to "{}"'.format(string, parsed))
	return parsed

def _get_attachments(message):
	"""Returns a list of attachments in an email Message."""
	return [part for part in message.get_payload() if
			part.get_content_disposition() == 'attachment']

def _write_attachment(attachment, mbox_file_path):
	"""Writes the attached file to an output directory."""
	attachments_path = os.path.join(os.path.dirname(mbox_file_path), 'extracted_attachments')
	timestamp = str(int(time.time()))  # use on collisions

	if not os.path.isdir(attachments_path):
		os.mkdir(attachments_path)

	filename = attachment.get_filename()
	if filename is None:
		return

	filename = strip_illegal_char(filename)
	path = os.path.join(attachments_path, filename)
	
	# If same filename, append with unique string
	if os.path.exists(path):
		original_path = path
		path = os.path.join(attachments_path, timestamp + '-' + filename)
		print('Renamed "{}" to "{}"'.format(original_path, path))

	try:
		with open(path, 'wb') as fb:
			fb.write(attachment.get_payload(decode=True))
			print('Saved "{}"'.format(path))
	except Exception as e:
		print('Error: ' + e)
		return

def extract_mail_attachments(mbox_file_path):
	"""Extracts and writes email attachments from an mbox archive."""
	mbox = mailbox.mbox(mbox_file_path)
	for message in mbox:
		# Right now I'm assuming attachments only exist on multipart messages. I
		# haven't read the specifications of the mbox file format.
		if message.is_multipart():
			for attachment in _get_attachments(message):
				_write_attachment(attachment, mbox_file_path)
```

**Comment by treymo** [comment]
Hey, thanks for this.  Are you planning on sending a Pull Request with the changes? I can make the changes you posted myself if you aren't planning on sending one

**Comment by slimninja** [comment]
Not planning on sending a pull request. Wasn't sure if you would want to clean this up either, so please go ahead and make changes as you deem fit! 

Unix systems allow some of those characters, so not sure if you want to strip only from windows, or just both so everything runs through.

And in hindsight maybe would be better to use os.path.splitext(path) and do `split[0] + '-' + timestamp + split[1]` to have the file as `path/samename-2020.png` vs `path/2020-samename.png'

**Comment by treymo** [comment]
I'll work on integrating these while I'm on holiday - thanks for debugging while using this!

**Comment by slimninja** [comment]
Np! Thanks for the development! This is more thorough/easier than I was searching gmail for photos manually when I attempted this a year ago. Let me find a lot of photos I thought I lost from back in early 2010's.

You should think about contacting the dev at https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper. I haven't used it yet (will do later this weekend most likely), but at a glance the photo parser looks more enhanced than yours as it reads the exif data and modifies the photos. The world needs the best google photo / mailbox parser!

**Comment by treymo** [comment]
Just submitted your proposed changes.  Do you mind giving it a test run if you have some takeout archives handy?  I'm working on restoring my backups of the archives but I don't have one handy to actually test the changes.

Oh nice, it looks like someone made an improved version of this project! I'll give it a look

**Comment by slimninja** [comment]
> Just submitted your proposed changes. Do you mind giving it a test run if you have some takeout archives handy? I'm working on restoring my backups of the archives but I don't have one handy to actually test the changes.
> 
> Oh nice, it looks like someone made an improved version of this project! I'll give it a look

Great! Dont have my archive handy anymore, deleted it after the last run and purged everything. Took a look at the code though, and it looks good! Cheers mate.
